### ISSUE TITLE
Linking error in dynamic::variable

### ISSUE THREAD

**Issue by vinipsmaker2** [breese/trial.protocol#8]
```
CMakeFiles/dynamic_dict_validator.dir/__/src/message_parsers/dynamic_dict_validator.cpp.o: In function `trial::protocol::dynamic::variable::map(std::initializer_list<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, trial::protocol::dynamic::variable> >)':
/home/blinktrade/Projetos/tradex/3rd/trial.protocol/include/trial/protocol/dynamic/detail/variable.ipp:964: multiple definition of `trial::protocol::dynamic::variable::map(std::initializer_list<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, trial::protocol::dynamic::variable> >)'
CMakeFiles/dynamic_dict_validator.dir/dynamic_dict_validator.cpp.o:/home/blinktrade/Projetos/tradex/3rd/trial.protocol/include/trial/protocol/dynamic/detail/variable.ipp:964: first defined here
CMakeFiles/dynamic_dict_validator.dir/__/src/message_parsers/dynamic_dict_validator.cpp.o: In function `trial::protocol::dynamic::variable::map()':
/home/blinktrade/Projetos/tradex/3rd/trial.protocol/include/trial/protocol/dynamic/detail/variable.ipp:959: multiple definition of `trial::protocol::dynamic::variable::map()'
CMakeFiles/dynamic_dict_validator.dir/dynamic_dict_validator.cpp.o:/home/blinktrade/Projetos/tradex/3rd/trial.protocol/include/trial/protocol/dynamic/detail/variable.ipp:959: first defined here
CMakeFiles/dynamic_dict_validator.dir/__/src/message_parsers/dynamic_dict_validator.cpp.o: In function `trial::protocol::json::basic_reader<char>::frame** std::__copy_move<false, true, std::random_access_iterator_tag>::__copy_m<trial::protocol::json::basic_reader<char>::frame*>(trial::protocol::json::basic_reader<char>::frame* const*, trial::protocol::json::basic_reader<char>::frame* const*, trial::protocol::json::basic_reader<char>::frame**)':
/home/blinktrade/Projetos/tradex/3rd/trial.protocol/include/trial/protocol/dynamic/detail/variable.ipp:944: multiple definition of `trial::protocol::dynamic::variable::null'
CMakeFiles/dynamic_dict_validator.dir/dynamic_dict_validator.cpp.o:/home/blinktrade/boost_1_61_0/boost/test/unit_test_suite.hpp:338: first defined here
CMakeFiles/dynamic_dict_validator.dir/__/src/message_parsers/dynamic_dict_validator.cpp.o: In function `std::_Deque_base<trial::protocol::json::basic_reader<char>::frame, std::allocator<trial::protocol::json::basic_reader<char>::frame> >::_Deque_impl::_M_swap_data(std::_Deque_base<trial::protocol::json::basic_reader<char>::frame, std::allocator<trial::protocol::json::basic_reader<char>::frame> >::_Deque_impl&)':
/home/blinktrade/Projetos/tradex/3rd/trial.protocol/include/trial/protocol/dynamic/detail/variable.ipp:948: multiple definition of `trial::protocol::dynamic::variable::array(std::initializer_list<trial::protocol::dynamic::variable>)'
CMakeFiles/dynamic_dict_validator.dir/dynamic_dict_validator.cpp.o:/home/blinktrade/Projetos/tradex/3rd/trial.protocol/include/trial/protocol/dynamic/detail/variable.ipp:948: first defined here
CMakeFiles/dynamic_dict_validator.dir/__/src/message_parsers/dynamic_dict_validator.cpp.o: In function `new_allocator':
/home/blinktrade/Projetos/tradex/3rd/trial.protocol/include/trial/protocol/dynamic/detail/variable.ipp:943: multiple definition of `trial::protocol::dynamic::variable::array()'
CMakeFiles/dynamic_dict_validator.dir/dynamic_dict_validator.cpp.o:/home/blinktrade/Projetos/tradex/3rd/trial.protocol/include/trial/protocol/dynamic/detail/variable.ipp:943: first defined here
clang: error: linker command failed with exit code 1 (use -v to see invocation)
test/CMakeFiles/dynamic_dict_validator.dir/build.make:127: recipe for target 'test/dynamic_dict_validator' failed
```

**Comment by vinipsmaker2** [comment]
Commit 376d45b55cbb1a2b4b5b656eb95c966babc0825e

**Comment by breese** [comment]
Fixed by 103f3c140a2a3b4390a9f5178abc360099335842

**Comment by vinipsmaker** [comment]
That's so weird. I still get errors:

```
CMakeFiles/request_message_parser.dir/__/src/message_parsers/dynamic_dict_validator.cpp.o:(.rodata+0x60): multiple definition of `trial::protocol::dynamic::variable::null'
CMakeFiles/request_message_parser.dir/request_message_parser.cpp.o:(.rodata+0x0): first defined here
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I don't understand why I get these errors. I mean, `trial::protocol::dynamic::variable::null` is constexpr!!!

It's defined exactly as in http://en.cppreference.com/w/cpp/types/integral_constant

**Comment by breese** [comment]
Which compiler version?

**Comment by vinipsmaker** [comment]
> Which compiler version?

```
blinktrade @ blinktrade ~/Projetos/tradex/build $ clang --version
clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by breese** [comment]
`std::integral_constant` is a template, `variable` is not. Therefore `variable::null` is declared in [variable.hpp](https://github.com/breese/trial.protocol/blob/feature/dynamic/include/trial/protocol/dynamic/variable.hpp#L95) but defined in [variable.ipp](https://github.com/breese/trial.protocol/blob/feature/dynamic/include/trial/protocol/dynamic/detail/variable.ipp#L842). Otherwise we would get a linker error.

Fortunately `variable` will be turned into a template to handle allocators, which should make this problem disappear. This was a low-priority task on my to-do list, but I will experdite it now.

**Comment by breese** [comment]
It just occurred to me that there is a mind-boggling simple solution to this ODR-violation: use an enum instead of a static constexpr.

Fixed in c6ce250924d176ed4af00c2d00935543105c6e5c

**Comment by vinipsmaker** [comment]
> It just occurred to me that there is a mind-boggling simple solution to this ODR-violation: use an enum instead of a static constexpr.

That was very creative.
